version: "3.5"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/mime.types:/etc/nginx/mime.types
      - ./nginx/certs:/var/uaimangas/certs
      - ./nginx/html:/var/uaimangas/html
    ports:
      - 80:80
      - 443:443
    networks:
      - api
      - nginx
    depends_on:
      - api
  db:
    image: mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./api/.env.prod
    volumes:
      - db-data:/var/lib/mysql
      # - ../MangaDump20200706:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3306:3306
    networks:
      - database
  api:
    container_name: manga-api
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    env_file:
      - ./api/.env.prod
    environment:
      NODE_ENV: prod
      GOOGLE_APPLICATION_CREDENTIALS: /home/firebase.json
    volumes:
      - ./uai-mangas-firebase-adminsdk-4xewi-819366107a.json:/home/firebase.json
    ports:
      - 3000:3000
    networks:
      - api
      - database
    depends_on:
      - db
  extrator:
    container_name: manga-extrator
    build:
      context: ./extrator/
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: prod
      GOOGLE_APPLICATION_CREDENTIALS: /home/firebase.json
    volumes:
      - ./uai-mangas-firebase-adminsdk-4xewi-819366107a.json:/home/firebase.json
    networks:
      - database
    depends_on:
      - db

networks:
  api:
    driver: bridge
  database:
  nginx:

volumes:
  db-data:
