name: leitor_manga
description: A new Flutter project.

publish_to: 'none'

version: 2.1.0+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^1.1.1
  http: ^0.12.1
  quiver: ^2.1.3
  progress_dialog: ^1.2.4
  diagonal_scrollview: ^0.2.0
  intl: ^0.16.1
  expandable: ^4.1.4
  dio: ^3.0.9
  extended_future_builder: any
  pedantic: ^1.8.0
  firebase_auth: ^0.16.1
  flutter_facebook_login: ^3.0.0
  equatable: ^1.2.2
  flutter_signin_button: ^1.0.0
  google_sign_in: ^4.5.1
  admob_flutter: "^1.0.0-beta.5"
  package_info: ^0.4.1
  firebase_messaging: ^6.0.16
  flushbar: ^1.10.4
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.5.0
  flutter_markdown: ^0.4.2
  shared_preferences: ^0.5.8
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+2
  flutter_modular: ^1.3.2
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.1

dependency_overrides:
  analyzer: 0.39.14 #https://github.com/dart-lang/sdk/issues/42887


flutter_native_splash:
  image: assets/images/splashscreen.png
  color: "2e2e2e"
  fill: true
  ios: false


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/md/

vars: 
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts: 
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs