name: Flutter CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: steebchen/flutter@v1.1.0
    - run: flutter pub get
      working-directory: ./mobile
    - run: flutter analyze
      name: Analyze code
      working-directory: ./mobile
