name: Flutter CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    name: Analyze project
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      uses: steebchen/flutter@v1.1.0
      with:
        args: pub get

    - name: analyze project
      uses: steebchen/flutter@v1.1.0
      with:
        args: analyze
